### ISSUE TITLE
Another Connection issue

### ISSUE THREAD

**Issue by talk2dug** [aster94/GoProControl#18]
Hey,

Trying to get this to work, Got it working on my 4s but my 7s won't connect. I keep getting failed With status 6. I can connect to it from my raspberry pi and laptop, but not his library. 

Any suggestions?

**Comment by talk2dug** [comment]
Ok, scratch that, all of. asuddon it started working.

Now I am getting 
Stack smashing protect failure!

abort() was called at PC 0x400dc980 on core 1

**Comment by talk2dug** [comment]
AAAAAAAAnd. Ill delete this thread...

**Comment by aster94** [comment]
Can you send your sketch and the complete log from the serial monitor?
