### ISSUE TITLE
setTimeLapseInterval error ?

### ISSUE THREAD

**Issue by roberto1963** [aster94/GoProControl#21]
Hello , 
Calling setTimeLapseInterval return a error when I call it (wrong parameter).
I think it is necessary to replace OR operations by AND operations in this line:

https://github.com/aster94/GoProControl/blob/2323f381f97ec14b305f264e04e9dae75d7ed8ad/src/GoProControl.cpp#L1095

When I change this line in :   
if (i_option != 0 && i_option != 1 && i_option != 5 && i_option != 10 && i_option != 30 && i_option != 60)
it works OK. 
Do you think it is ok ?
Roberto

**Comment by aster94** [comment]
Can you post an extract of the code you are using?

**Comment by roberto1963** [comment]
I only change all the || with && in the line 1095 and it works .

Here is the way I call timelapse mode :

  gp.begin ();
  gp.begin ();
  gp.turnOn();
  gp.setTimeLapseInterval(1);
  gp.setMode(TIMELAPSE_MODE);   
  gp.shoot();

**Comment by aster94** [comment]
I checked this only now and you were absolutely right|
