### ISSUE TITLE
Hero7 Silver

### ISSUE THREAD

**Issue by dushyantahuja** [aster94/GoProControl#23]
Just found this library, and loved the concept. However, installed the GoProControl.ino example and tried to make it work. I updated the Secrets.h file, but was not able to connect to the Hero7 Silver at all. KonradIT mentions that the calls work with the Hero7 Silver https://github.com/KonradIT/goprowifihack/tree/master/HERO7 -so not sure what I'm doing wrong. Any help would be appreciated.

**Comment by dushyantahuja** [comment]
To try to debug this, I connected to the GoPro's wifi using my computer and opened the links in KonradITs documentation. They work, but the ESP8266 is simply not able to connect. I even changed the WiFi of the camera to 2.6 GHz - but still didn't work.

**Comment by KonradIT** [comment]
We need log details from the ESP8266, to understand why the HTTP requests are not getting through.

**Comment by dushyantahuja** [comment]
Closing this now - I was an idiot, and didn't realise that I had to click 'b' first to 'begin' the connection. It's working now - thanks a lot.

**Comment by aster94** [comment]
Set the wifi to 2.4GHz is mandatory since the esp8266 doesn't handle 5GHz.
as kondard said please paste a log of the serial with debug enabled

**Comment by aster94** [comment]
never mind, have fun with the library, be aware that the ESP8266 have some limitations
