### ISSUE TITLE
GoPro8 connection failed

### ISSUE THREAD

**Issue by maxholgasson** [aster94/GoProControl#28]
Hi, using your latest lib with a gopro8 I'm getting "Connection failed with status: 6" and after pressing "b" for some more time "Connection failed with status: 1"
I couldnt find hints about this errors in the documentation. Could you help me to find a solution?

**Comment by aster94** [comment]
you need to turn on the wifi via ble, at this time the only way to do it is with the app

https://github.com/aster94/GoProControl/issues/26
