### ISSUE TITLE
Nothing is showing on serial monitor by using wemos d1mini

### ISSUE THREAD

**Issue by akseerali** [aster94/GoProControl#31]
I have followed all the steps but nothing is showing on wemos d1mini's serial monitor. When I type anything it says, " connect the camera first". The serial monitor is not showing 'connecting to the wifi' even when resetting the d1 mini.

**Comment by aster94** [comment]
> connect the camera first

have you connected the camera?

**Comment by akseerali** [comment]
this d1 mini is not connecting itself to the camera, neither there is output on the serial monitor.
