### ISSUE TITLE
Connection failed: New GoPro Firmware ?

### ISSUE THREAD

**Issue by maxledfreak** [aster94/GoProControl#32]
Hello,

tried to connect with GoPro 8 camera. Code is running with Arduino and PlatformIO IDE. Feedback with example code is "Connection failed with status: 6". GoPro Quick App is working fine to control GoPro. Maybe there is a new way to connect to camera because after switch of bluetooth on my mobile phone, can not connect to GoPro with GoPro Quick App. Looks like that GoPro is only able to do Wifi pairing after sending specific bluetooth command. 

Greetings
Max

**Comment by aster94** [comment]
see if this help https://github.com/aster94/GoProControl/issues/26

I used it with gopro max which should be similar to 8
