### ISSUE TITLE
Having trouble with GoPro Hero7 and ESP8266

### ISSUE THREAD

**Issue by FunnyBunny89** [aster94/GoProControl#37]
I saw this comment "ESP8266 can't get the BSSID of the camera. So if you want to turn it on you need to manually pass it to the constructor, see the docs" but how do I get it to work and how to get the BSSID form the camera and where to put that information.

**Comment by aster94** [comment]
You can find on Google how to get the bssid of your camera.
The constructor is this:
https://github.com/aster94/GoProControl/blob/33a5db059c73098c918698a8a08ae10a26a95ca5/src/GoProControl.h#L76

Il mer 14 lug 2021, 19:12 FunnyBunny89 ***@***.***> ha
scritto:
