### ISSUE TITLE
HERO8 usage with ESP8266

### ISSUE THREAD

**Issue by fabian57fabian** [aster94/GoProControl#38]
Hello, i have a NodeMCU ESP8266.
I tried to upload the sketch but i cant':

-find the baud rate (i tried with 74880)

Could you tell me if you tried it?

**Comment by aster94** [comment]
default 115200
https://github.com/aster94/GoProControl/blob/c49fdf4b2fef6f9f097fda5e80a16553c65d1447/src/GoProControl.h#L142-L143
change as you wish in the function
