### ISSUE TITLE
Unable to connect after reset ESP8266

### ISSUE THREAD

**Issue by tommy-b-10** [aster94/GoProControl#39]
Hi, I am having an issue similar to [here](https://github.com/aster94/GoProControl/issues/29)

The camera and ESP connect together correctly, until the ESP is reset. It then fails on _wifi_client.connect().
To get the connection working again, the camera WiFi service must be restarted.

Is there any solution to this? I have tried disconnecting wifi and then restarting the ESP8266 but this was not successful.

Thanks!

Other similar issues:
https://github.com/esp8266/Arduino/issues/5552
https://github.com/KonradIT/goprowifihack/issues/193

**Comment by aster94** [comment]
I guess the problem is due to the wrong untethering when your esp resets, you have to avoid it by programatically
